source 'http://rubygems.org'

gem 'sinatra', "~> 2.1"
gem 'activerecord', '~> 5.1', '>= 4.2.6', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'rack-contrib', '~> 2.3'
gem 'rack-cors', '~> 1.1'
gem 'require_all'
gem 'rerun'
gem 'sqlite3', '~> 1.3.6'
gem 'thin', "~> 1.8"
gem 'pry'
gem 'bcrypt'
gem 'tux'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
